apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-named-port
  namespace: practice-a-maxmudov
  labels:
    application: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
        ports:
        - name: http-port
          containerPort: 80

