apiVersion: v1
kind: Pod
metadata:
  name: busybox-echo
  labels:
    name: busybox-echo
spec:
  containers:
  - name: busybox-echo
    image: busybox
    command: ["/bin/echo"]
    args: ["Hello World"]
    
