apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: practice-a-maxmudov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: nvrbckdown/flask-app:v1
        ports:
        - name: flask-port
          containerPort: 5000
        
