apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    name: flaskapp
spec:
  ingressClassName: nginx
  rules:
  - host: amahmudov.nvrbckdown.uz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: flaskapp
            port: 
              number: 5000
