apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: practice-a-maxmudov
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        env:
        - name: my_token
        valueFrom:
        secretKeyRef:
        name: TOKEN
        key: password
